### ISSUE TITLE
Roadmap 1.0.0

### ISSUE THREAD

**Issue by zamotany** [zamotany/react-slate#99]
#### TODO:
- [x] `renderToJson` function
- [x] `renderToString` function
- [x] support for `NO_COLOR`
- [x] `render` function
- [x] alternative screen buffer with `render`
- [x] gracefully exit if errors are throw
- [x] `console` functions logging to main screen buffer upon exit
- [x] `Text` and `View` components
- [x] basic styling supported by `colorette`
- [x] layout support with https://github.com/vislyhq/stretch
- [x] RGA colors
- [x] keyboard events (via `terminal` from `terminal-kit`)
- [x] mouse events (via `terminal` from `terminal-kit`)
- [x] `Progress` component
- [x] `Spinner` component
- [x] `onLayout` hook
- [x] `onClick` hook
- [x] `renderToJson` support for continuous rendering with infinite `Promise` iterator
- [x] `renderToString` support for continuous rendering with infinite `Promise` iterator
- [x] tests:
   - [x] nodes
   - [x] renderer
   - [x] `renderToJson`
   - [x] `renderToString`
   - [x] components
- [x] Documentation
- [x] absolute positioning
- [x] allow nesting `Text` components
- [x] redo `Progress` component
- [x] `onMouseWheel` hook
- [x] refactor `onClick` and `onMouseWheel` event propagation for better performance
- [x] Refactor painting (recursive Canvas filling & merging)
- [x] fix progress bar scaling issue when resizing
- [x] Haul dashboard example
- [x] add README to `@react-slate/core` package
- [ ] `FlatList` component

## Future

- [ ] add canvas caching to speed up painting
- [ ] `@react-slate/testing-library` (__?__)
- [ ] `@react-slate/web-render` (__?__)
